admin_demande:
    resource: "@AdminBundle/Controller/DemandeController.php"
    type:     annotation

admin_categorie:
    resource: "@AdminBundle/Controller/CategorieController.php"
    type:     annotation

admin_annonce:
    resource: "@AdminBundle/Controller/AnnonceController.php"
    type:     annotation

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /
